### ISSUE TITLE
Runtime error when training imitation learning model

### ISSUE THREAD

**Issue by duckieT** [duckietown/gym-duckietown#125]
After running `experiments/train_imitation.py --map-name loop_obstacles`, I got this error:

RuntimeError: size mismatch, m1: [2 x 62016], m2: [2816 x 256 ] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249

Can anyone please help :(

**Comment by bhairavmehta95** [comment]
So the `train_imitation` code is probably quite old, in which case the convolution filters will not produce the same size output as they used to (We changed the image size that comes out of the simulator).

You can take a look at the model getting called and edit the numbers explictly (it should be in the first fully connected layer). I will have some time early next week to fix it otherwise.

**Comment by bhairavmehta95** [comment]
Follow in #124 and #130
